### ISSUE TITLE
implicit declaration of function 'pinMatrixOutAttach'

### ISSUE THREAD

**Issue by Ivorforce** [bbulkow/FastLED-idf#9]
I got further some steps, and now I'm getting a compile failure on various hal-files.

I traced back the steps and this function seems to be usually declared in `esp32-hal-matrix.h`, which is not included in this distribution.

I have to add I'm using platformio's Arduino / esp-idf special cocktail mix, and the arduino framework adds those header files itself too. Though it does not seem to be compiled along with this in this case.

Some excerpt:

```
.pio/libdeps/esp32dev/FastLED-idf/components/FastLED-idf/hal/esp32-hal-spi.c: In function 'spiAttachSCK':
.pio/libdeps/esp32dev/FastLED-idf/components/FastLED-idf/hal/esp32-hal-spi.c:88:5: error: implicit declaration of function 'pinMatrixOutAttach' [-Werror=implicit-function-declaration]
     pinMatrixOutAttach(sck, SPI_CLK_IDX(spi->num), false, false);
     ^~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
*** [.pio/build/esp32dev/libae2/FastLED-idf/components/FastLED-idf/hal/esp32-hal-rmt.c.o] Error 1
.pio/libdeps/esp32dev/FastLED-idf/components/FastLED-idf/hal/esp32-hal-spi.c: In function 'spiAttachMISO':
.pio/libdeps/esp32dev/FastLED-idf/components/FastLED-idf/hal/esp32-hal-spi.c:107:5: error: implicit declaration of function 'pinMatrixInAttach' [-Werror=implicit-function-declaration]
     pinMatrixInAttach(miso, SPI_MISO_IDX(spi->num), false);
     ^~~~~~~~~~~~~~~~~
```

**Comment by bbulkow** [comment]
Since I don't use platformio, I can't reproduce this. Happy to take a pull request of your fix though.

**Comment by bbulkow** [comment]
Rather interesting. The file that was annoying you isn't used, the hal files aren't for both of those --- the RMT system is direct and doesn't need an arduino "shim".

Thus, I've removed the files and references to them. I can only assume that PlatformIO is simply taking all the C files and compiling them, instead of looking in the CMakeLists.txt and trying to figure out what files are actually used.

Let me know if this is resolved.
